
-- Table: BCK_ACCOUNT_DM
CREATE TABLE BCK_ACCOUNT_DM (
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	ACCOUNT_TYPE 		VARCHAR2(8)				, 
	HOLDING_NUMBER 		VARCHAR2(32)			, 
	ACCOUNT_NUMBER 		VARCHAR2(32)			, 
	CUSTOM_1 			VARCHAR2(30)			, 
	CUSTOM_2 			VARCHAR2(30)			, 
	CUSTOM_3 			VARCHAR2(30)
); 

ALTER TABLE BCK_ACCOUNT_DM ADD CONSTRAINT BCK_ACCOUNT_DM_PK
	 PRIMARY KEY (OBJID);
	 
CREATE INDEX BCK_ACCOUNT_IDX1 ON  BCK_ACCOUNT_DM (ACCOUNT_NUMBER);
CREATE UNIQUE INDEX BCK_ACCOUNT_IDX2 ON  BCK_ACCOUNT_DM (ACCOUNT_TYPE, ACCOUNT_NUMBER);

-- Table: BCK_CARRIER_DM
CREATE TABLE  BCK_CARRIER_DM (
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	CARRIER_NAME 		VARCHAR2(48)			, 
	CARRIER_CODE 		VARCHAR2(8)		NOT NULL, 
	CARRIER_STATE 		VARCHAR2(8)		NOT NULL, 
	CUSTOM_1 			VARCHAR2(30)			, 
	CUSTOM_2 			VARCHAR2(30)			, 
	CUSTOM_3 			VARCHAR2(30) 
);

ALTER TABLE BCK_CARRIER_DM ADD CONSTRAINT BCK_CARRIER_DM_PK
	 PRIMARY KEY (OBJID);

CREATE UNIQUE INDEX BCK_CARRIER_IDX1 ON  BCK_CARRIER_DM (CARRIER_CODE, CARRIER_STATE);

-- Table: BCK_CARRIER_DATA
CREATE TABLE  BCK_CARRIER_DATA (
	OBJID 						NUMBER(19,0) 	NOT NULL,
	CARRIER_FULL_NAME			VARCHAR2(128)			,
	CARRIER_TAX_ID				VARCHAR2(24)			,
	CARRIER_STATE_ENROLL_NBR	VARCHAR2(32)			,
	CARRIER_CITY_ENROLL_NBR		VARCHAR2(32)			,
	ADDR_STREET					VARCHAR2(128)			,
	ADDR_NUMBER					VARCHAR2(32)			,
	ADDR_COMPLEMENT				VARCHAR2(32)			,
	ADDR_ZIP					VARCHAR2(16)			,
	ADDR_CITY					VARCHAR2(64)			,
	ADDR_WEB					VARCHAR2(64)			,
	ADDR_EMAIL					VARCHAR2(64)			,
	CARRIER_DM_UID				NUMBER(19,0)	NOT NULL,
	CUSTOM_1					VARCHAR2(30)			,
	CUSTOM_2					VARCHAR2(30)			, 
	CUSTOM_3					VARCHAR2(30)
);

ALTER TABLE BCK_CARRIER_DATA ADD CONSTRAINT BCK_CARRIER_DATA_PK
	 PRIMARY KEY (OBJID);

ALTER TABLE BCK_CARRIER_DATA ADD CONSTRAINT BCK_CARRIER_DATA_FK1
	 FOREIGN KEY (CARRIER_DM_UID) REFERENCES BCK_CARRIER_DM (OBJID);

CREATE UNIQUE INDEX BCK_CARRIER_DATA_IDX1 ON  BCK_CARRIER_DATA (CARRIER_DM_UID);

-- Table: BCK_CYCLE_DM
CREATE TABLE BCK_CYCLE_DM (
	OBJID	 			NUMBER(19,0) 	NOT NULL, 
	CYCLE_CODE 			VARCHAR2(8)				, 
	CUT_DATE 			DATE					, 
	ISSUE_DATE 			DATE					, 
	DUE_DATE 			DATE					, 
	CUSTOM_1 			VARCHAR2(30 CHAR)		, 
	CUSTOM_2 			VARCHAR2(30 CHAR)		, 
	CUSTOM_3 			VARCHAR2(30 CHAR)
); 

ALTER TABLE BCK_CYCLE_DM ADD CONSTRAINT BCK_CYCLE_DM_PK PRIMARY KEY (OBJID);
	 
CREATE UNIQUE INDEX BCK_CYCLE_IDX1 ON  BCK_CYCLE_DM (CYCLE_CODE, CUT_DATE, DUE_DATE);
	 

-- due to problems with JPivot
CREATE OR REPLACE FORCE VIEW BCK_CYCLE_DM_VIEW 
	(OBJID, CYCLE_CODE, CUT_DATE, ISSUE_DATE, DUE_DATE) AS 
	( SELECT OBJID, CYCLE_CODE, to_char(CUT_DATE) as CUT_DATE, 
	         to_char(ISSUE_DATE) as ISSUE_DATE, 
	         to_char(DUE_DATE) as DUE_DATE
  from BCK_CYCLE_DM );

-- Table: BCK_GEO_DM
CREATE TABLE BCK_GEO_DM (
	OBJID 					NUMBER(19,0) 	NOT NULL, 
	GEO_COUNTRY 			VARCHAR2(32)			,
	GEO_REGION 				VARCHAR2(16)			,
	GEO_STATE 				VARCHAR2(2)				,
	GEO_CITY 				VARCHAR2(64)			,
	CUSTOM_1 				VARCHAR2(30)			,
	CUSTOM_2 				VARCHAR2(30)			, 
	CUSTOM_3 				VARCHAR2(30)
);	
	
ALTER TABLE BCK_GEO_DM ADD CONSTRAINT BCK_GEO_DM_PK
	 PRIMARY KEY (OBJID);

CREATE UNIQUE INDEX BCK_GEO_IX01 ON BCK_GEO_DM (GEO_COUNTRY, GEO_STATE, GEO_CITY);

-- Table: BCK_TAX_TYPE
CREATE TABLE BCK_TAX_TYPE (
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	TAX_CODE 			VARCHAR2(10)	NOT NULL, 
	TAX_NAME			VARCHAR2(64)	NOT NULL, 
	CUSTOM_1			VARCHAR2(30)			,
	CUSTOM_2			VARCHAR2(30)			, 
	CUSTOM_3			VARCHAR2(30)
);	
	
ALTER TABLE BCK_TAX_TYPE ADD CONSTRAINT BCK_TAX_TYPE_PK
	 PRIMARY KEY (OBJID);

-- Table: BCK_FISCAL_CODE
CREATE TABLE BCK_FISCAL_CODE (
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	FISCAL_CODE			VARCHAR2(10)	NOT NULL, 
	CODE_DESCRIPTION	VARCHAR2(128)	NOT NULL, 
	CUSTOM_1			VARCHAR2(30)			,
	CUSTOM_2			VARCHAR2(30)			, 
	CUSTOM_3			VARCHAR2(30)
);	
	
ALTER TABLE BCK_FISCAL_CODE ADD CONSTRAINT BCK_FISCAL_CODE_PK
	 PRIMARY KEY (OBJID);

CREATE UNIQUE INDEX BCK_FISCAL_CODE_IX01 ON BCK_FISCAL_CODE (FISCAL_CODE);

-- Table: BCK_TAX_RATE
CREATE TABLE BCK_TAX_RATE (
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	TAX_RATE			NUMBER(6,4)		NOT NULL, 
	GEO_UID				NUMBER(19,0)	NOT NULL, 
	TAX_TYPE_UID		NUMBER(19,0)	NOT NULL, 
	FISCAL_CODE_UID		NUMBER(19,0)			, 
	CUSTOM_1			VARCHAR2(30)			,
	CUSTOM_2			VARCHAR2(30)			, 
	CUSTOM_3			VARCHAR2(30)
);	

ALTER TABLE BCK_TAX_RATE ADD CONSTRAINT BCK_TAX_RATE_PK
	 PRIMARY KEY (OBJID);

ALTER TABLE BCK_TAX_RATE ADD CONSTRAINT BCK_TAX_RATE_FK1
	 FOREIGN KEY (GEO_UID) REFERENCES BCK_GEO_DM (OBJID);

ALTER TABLE BCK_TAX_RATE ADD CONSTRAINT BCK_TAX_RATE_FK2
	 FOREIGN KEY (TAX_TYPE_UID) REFERENCES BCK_TAX_TYPE (OBJID);

ALTER TABLE BCK_TAX_RATE ADD CONSTRAINT BCK_TAX_RATE_FK3
	 FOREIGN KEY (FISCAL_CODE_UID) REFERENCES BCK_FISCAL_CODE (OBJID);

CREATE UNIQUE INDEX BCK_TAX_RATE_IX01 ON BCK_TAX_RATE (GEO_UID, TAX_TYPE_UID, FISCAL_CODE_UID);

-- Table: BCK_TIME_DM
CREATE TABLE BCK_TIME_DM (
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	TIME_YEAR 			VARCHAR2(4)				, 
	TIME_MONTH 			VARCHAR2(2)				, 
	TIME_DAY 			VARCHAR2(2)				, 
	CUSTOM_1 			VARCHAR2(30)			,
	CUSTOM_2 			VARCHAR2(30)			,
	CUSTOM_3 			VARCHAR2(30)
);
 
ALTER TABLE BCK_TIME_DM ADD CONSTRAINT BCK_TIME_DM_PK
	 PRIMARY KEY (OBJID);

CREATE UNIQUE INDEX BCK_TIME_IDX1 ON  BCK_TIME_DM (TIME_YEAR, TIME_MONTH, TIME_DAY);


-- Table: BCK_RULE_TYPE
CREATE TABLE BCK_RULE_TYPE (
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	TYPE_NAME 			VARCHAR2(32) 	NOT NULL, 
	DESCRIPTION 		VARCHAR2(128)			, 
	CUSTOM_1 			VARCHAR2(30)			, 
	CUSTOM_2 			VARCHAR2(30)			, 
	CUSTOM_3 			VARCHAR2(30)
);

ALTER TABLE BCK_RULE_TYPE ADD CONSTRAINT BCK_RULE_TYPE_PK
	 PRIMARY KEY (OBJID); 
	 
ALTER TABLE BCK_RULE_TYPE ADD CONSTRAINT BCK_RULE_TYPE_UK1
	 UNIQUE (TYPE_NAME);


-- Table: BCK_RULE
CREATE TABLE BCK_RULE (	
	OBJID 				NUMBER(19,0) 	NOT NULL, 
	RULE_CODE 			VARCHAR2(16) 	NOT NULL, 
	RULE_NAME 			VARCHAR2(32) 	NOT NULL, 
	DESCRIPTION 		VARCHAR2(128)			, 
	RULE_TYPE_UID 		NUMBER(19,0)			, 
	CUSTOM_1 			VARCHAR2(30)			, 
	CUSTOM_2 			VARCHAR2(30)			, 
	CUSTOM_3 			VARCHAR2(30)
);

ALTER TABLE BCK_RULE ADD CONSTRAINT BCK_RULE_PK
	 PRIMARY KEY (OBJID);
	 
ALTER TABLE BCK_RULE ADD CONSTRAINT BCK_RULE_UK1
	 UNIQUE (RULE_CODE);

ALTER TABLE BCK_RULE ADD CONSTRAINT BCK_RULE_FK1
	FOREIGN KEY (RULE_TYPE_UID) REFERENCES BCK_RULE_TYPE (OBJID);

-- Table: BCK_CONSEQUENCE_ATTR
CREATE TABLE BCK_CONSEQUENCE_ATTR (
	 OBJID NUMBER(19,0) NOT NULL, 
   ATTR_NAME_1 VARCHAR2(32),
   ATTR_VALUE_1 VARCHAR2(128),
   ATTR_NAME_2 VARCHAR2(32),
   ATTR_VALUE_2 VARCHAR2(128),
   ATTR_NAME_3 VARCHAR2(32),
   ATTR_VALUE_3 VARCHAR2(128),
   ATTR_NAME_4 VARCHAR2(32),
   ATTR_VALUE_4 VARCHAR2(128),
   ATTR_NAME_5 VARCHAR2(32),
   ATTR_VALUE_5 VARCHAR2(128),
   ATTR_NAME_6 VARCHAR2(32),
   ATTR_VALUE_6 VARCHAR2(128),
   ATTR_NAME_7 VARCHAR2(32),
   ATTR_VALUE_7 VARCHAR2(128),
   ATTR_NAME_8 VARCHAR2(32),
   ATTR_VALUE_8 VARCHAR2(128),
   ATTR_NAME_9 VARCHAR2(32),
   ATTR_VALUE_9 VARCHAR2(128),
   ATTR_NAME_10 VARCHAR2(32),
   ATTR_VALUE_10 VARCHAR2(128),
   ATTR_NAME_11 VARCHAR2(32),
   ATTR_VALUE_11 VARCHAR2(128),
   ATTR_NAME_12 VARCHAR2(32),
   ATTR_VALUE_12 VARCHAR2(128),
   ATTR_NAME_13 VARCHAR2(32),
   ATTR_VALUE_13 VARCHAR2(128),
   ATTR_NAME_14 VARCHAR2(32),
   ATTR_VALUE_14 VARCHAR2(128),
   ATTR_NAME_15 VARCHAR2(32),
   ATTR_VALUE_15 VARCHAR2(128),
   ATTR_NAME_16 VARCHAR2(32),
   ATTR_VALUE_16 VARCHAR2(128),
   ATTR_NAME_17 VARCHAR2(32),
   ATTR_VALUE_17 VARCHAR2(128),
   ATTR_NAME_18 VARCHAR2(32),
   ATTR_VALUE_18 VARCHAR2(128),
   ATTR_NAME_19 VARCHAR2(32),
   ATTR_VALUE_19 VARCHAR2(128),
   ATTR_NAME_20 VARCHAR2(32),
   ATTR_VALUE_20 VARCHAR2(128)
);

ALTER TABLE BCK_CONSEQUENCE_ATTR ADD CONSTRAINT BCK_CONSEQUENCE_ATTR_PK
	 PRIMARY KEY (OBJID); 

 
-- Table: BCK_CONSEQUENCE
CREATE TABLE  BCK_CONSEQUENCE (	
 	OBJID 				NUMBER(19,0) 	NOT NULL, 
	ACCOUNT_UID 		NUMBER(19,0) 	NOT NULL,
	CARRIER_UID 		NUMBER(19,0) 	NOT NULL,
	CYCLE_UID 			NUMBER(19,0) 	NOT NULL,
	GEO_UID 			NUMBER(19,0) 	NOT NULL,
	TIME_UID 			NUMBER(19,0) 	NOT NULL,
	RULE_UID 			NUMBER(19,0) 	NOT NULL,
	TRANSACTION_ID 		VARCHAR2(64)			, 
	DESCRIPTION 		VARCHAR2(128)			, 
	CONSEQUENCE_LEVEL 	VARCHAR2(10) 	NOT NULL,
    ATTRIBUTE_UID       NUMBER(19)      NOT NULL,
    FILENAME            VARCHAR2(256)           ,
	CUSTOM_1 			VARCHAR2(30)			, 
	CUSTOM_2 			VARCHAR2(30)			, 
	CUSTOM_3 			VARCHAR2(30)			, 
	CUSTOM_4 			VARCHAR2(30)			, 
	CUSTOM_5 			VARCHAR2(30)
);

ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_PK
	PRIMARY KEY (OBJID); 
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK1
	 FOREIGN KEY (ACCOUNT_UID) REFERENCES BCK_ACCOUNT_DM (OBJID);
	  
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK2
	FOREIGN KEY (TIME_UID) REFERENCES BCK_TIME_DM (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK3
	FOREIGN KEY (RULE_UID) REFERENCES BCK_RULE (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK4
	FOREIGN KEY (GEO_UID) REFERENCES BCK_GEO_DM (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK5
	FOREIGN KEY (CARRIER_UID) REFERENCES BCK_CARRIER_DM (OBJID);
	
ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK6
	FOREIGN KEY (CYCLE_UID) REFERENCES BCK_CYCLE_DM (OBJID);

ALTER TABLE BCK_CONSEQUENCE ADD CONSTRAINT BCK_CONSEQUENCE_FK7
  FOREIGN KEY (ATTRIBUTE_UID) REFERENCES BCK_CONSEQUENCE_ATTR (OBJID);
  
  
CREATE UNIQUE INDEX BCK_CONSEQUENCE_IDX1 ON BCK_CONSEQUENCE (ATTRIBUTE_UID);  

CREATE INDEX BCK_CONSEQUENCE_IDX_2 ON BCK_CONSEQUENCE (TRANSACTION_ID, RULE_UID)


-- sequences	 
CREATE SEQUENCE BCK_CONSEQUENCE_UID INCREMENT BY 1 START WITH 1;
CREATE SEQUENCE BCK_DIMENSIONS_UID INCREMENT BY 1 START WITH 1;


--Table: BCK_INVOICE_SECTION
CREATE TABLE BCK_INVOICE_SECTION (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	SECTION_SHORT_NAME  VARCHAR2(10)  	NOT NULL,
	SECTION_DESCRIPTION VARCHAR2(64)   	        ,
	CARRIER_UID         NUMBER(19,0) 	NOT NULL,
	CUSTOM_1	        VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);

ALTER TABLE BCK_INVOICE_SECTION ADD CONSTRAINT BCK_INVOICE_SECTION_PK
PRIMARY KEY(OBJID);

ALTER TABLE BCK_INVOICE_SECTION ADD CONSTRAINT BCK_INVOICE_SECTION_FK1
	 FOREIGN KEY (CARRIER_UID) REFERENCES BCK_CARRIER_DM (OBJID);

CREATE UNIQUE INDEX BCK_INVOICE_SECTION_IX01 ON BCK_INVOICE_SECTION (SECTION_SHORT_NAME);

--Table: BCK_INVOICE_ALLOWED_CAPTIONS
CREATE TABLE BCK_INVOICE_ALLOWED_CAPTIONS (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	ALLOWED_CAPTION     VARCHAR2(64)	NOT NULL,
	SECTION_UID         NUMBER(19,0)	NOT NULL,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);

ALTER TABLE BCK_INVOICE_ALLOWED_CAPTIONS ADD CONSTRAINT BCK_INVOICE_ALLOWED_PK
PRIMARY KEY(OBJID);

ALTER TABLE BCK_INVOICE_ALLOWED_CAPTIONS ADD CONSTRAINT BCK_INVOICE_ALLOWED_FK1
	 FOREIGN KEY (SECTION_UID) REFERENCES BCK_INVOICE_SECTION(OBJID);



--
-- THRESHOLD TABLES 
--

--Table: BCK_PARM_USAGE_THRESHOLD
CREATE TABLE BCK_PARM_USAGE_THRESHOLD (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	HOME_FLAG			CHAR(1)			NOT NULL,
	COLLECT_FLAG		CHAR(1)			NOT NULL,
	RELATIVE_FLAG		CHAR(1)			NOT NULL,
	CALL_TYPE			INTEGER			NOT NULL,
	TIME_PERIOD			INTEGER			NOT NULL,
	DESTINATION_TYPE	INTEGER			NOT NULL,
	USAGE_TYPE			INTEGER			NOT NULL,
	LOWER_LIMIT			NUMBER(19,4)			,
	UPPER_LIMIT			NUMBER(19,4)			,
	LOWER_DURATION		NUMBER(19,0)			,
	UPPER_DURATION		NUMBER(19,0)			,
	HINT_MESSAGE		VARCHAR2(128)			,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);


ALTER TABLE BCK_PARM_USAGE_THRESHOLD ADD CONSTRAINT BCK_PARM_USAGE_THRESHOLD_PK
	PRIMARY KEY(OBJID);

CREATE UNIQUE INDEX BCK_PARM_USAGE_THRESHOLD_IDX1 ON BCK_PARM_USAGE_THRESHOLD 
	(HOME_FLAG, COLLECT_FLAG, RELATIVE_FLAG, CALL_TYPE, TIME_PERIOD,
	 DESTINATION_TYPE, USAGE_TYPE );
	 
--Table: BCK_PARM_OCC_THRESHOLD
CREATE TABLE BCK_PARM_OCC_THRESHOLD (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	CARRIER_UID         NUMBER(19,0)	NOT NULL,
	LOWER_LIMIT			NUMBER(19,4)			,
	UPPER_LIMIT			NUMBER(19,4)			,
	HINT_MESSAGE		VARCHAR2(128)			,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);


ALTER TABLE BCK_PARM_OCC_THRESHOLD ADD CONSTRAINT BCK_PARM_OCC_THRESHOLD_PK
PRIMARY KEY(OBJID);

ALTER TABLE BCK_PARM_OCC_THRESHOLD ADD CONSTRAINT BCK_PARM_OCC_THRESHOLD_FK1
FOREIGN KEY (CARRIER_UID) REFERENCES BCK_CARRIER_DM (OBJID);

CREATE UNIQUE INDEX BCK_PARM_OCC_THRESHOLD_IDX1 ON BCK_PARM_OCC_THRESHOLD (CARRIER_UID);


--Table: BCK_PARM_NF_THRESHOLD
CREATE TABLE BCK_PARM_NF_THRESHOLD (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	LOCAL_FLAG			CHAR(1)			NOT NULL,
	LOWER_LIMIT			NUMBER(19,4)			,
	UPPER_LIMIT			NUMBER(19,4)			,
	HINT_MESSAGE		VARCHAR2(128)			,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);


ALTER TABLE BCK_PARM_NF_THRESHOLD ADD CONSTRAINT BCK_PARM_NF_THRESHOLD_PK
	PRIMARY KEY(OBJID);

CREATE UNIQUE INDEX BCK_PARM_NF_THRESHOLD_IDX1 ON BCK_PARM_NF_THRESHOLD (LOCAL_FLAG);
	 

--Table: BCK_PARM_CUST_TYPE
CREATE TABLE BCK_PARM_CUST_TYPE (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	CUST_TYPE			VARCHAR2(4)		NOT NULL,
	DESCRIPTION			VARCHAR2(40)			,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);

ALTER TABLE BCK_PARM_CUST_TYPE ADD CONSTRAINT BCK_PARM_CUST_TYPE_PK
	PRIMARY KEY(OBJID);

CREATE UNIQUE INDEX BCK_PARM_CUST_TYPE_UK1 ON BCK_PARM_CUST_TYPE 
	(CUST_TYPE);


--Table: BCK_PARM_INVOICE_THRESHOLD
CREATE TABLE BCK_PARM_INVOICE_THRESHOLD (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	CUST_TYPE_UID		NUMBER(19,0)			,
	GEO_UID				NUMBER(19,0)			,
	LOWER_LIMIT			NUMBER(19,4)			,
	UPPER_LIMIT			NUMBER(19,4)			,
	HINT_MESSAGE		VARCHAR2(128)			,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);


ALTER TABLE BCK_PARM_INVOICE_THRESHOLD ADD CONSTRAINT BCK_PARM_INVOICE_THRESHOLD_PK
	PRIMARY KEY(OBJID);

ALTER TABLE BCK_PARM_INVOICE_THRESHOLD ADD CONSTRAINT BCK_PARM_INVOICE_THRESHOLD_FK1
	FOREIGN KEY (CUST_TYPE_UID) REFERENCES BCK_PARM_CUST_TYPE (OBJID);
	
ALTER TABLE BCK_PARM_INVOICE_THRESHOLD ADD CONSTRAINT BCK_PARM_INVOICE_THRESHOLD_FK2
	FOREIGN KEY (GEO_UID) REFERENCES BCK_GEO_DM (OBJID);

CREATE UNIQUE INDEX BCK_PARM_INV_THRESHOLD_IDX1 ON BCK_PARM_INVOICE_THRESHOLD 
	(CUST_TYPE_UID, GEO_UID);

-- Table: BCK_PARM_CYCLE_DATES
CREATE TABLE BCK_PARM_CYCLE_DATES (
	OBJID  				NUMBER(19,0)	NOT NULL,
	CYCLE_CODE 			VARCHAR2(8) 	NOT NULL,
	CUST_TYPE_UID		NUMBER(19)				,
	END_DATE 			DATE			NOT NULL,
	DUE_DATE 			DATE			NOT NULL,
	START_DATE 			DATE					,
	ISSUE_DATE 			DATE					,
	REF_DATE 			DATE					,
	CUSTOM_1 			VARCHAR2(30)			,
	CUSTOM_2 			VARCHAR2(30)			,
	CUSTOM_3 			VARCHAR2(30)
);

ALTER TABLE BCK_PARM_CYCLE_DATES ADD CONSTRAINT BCK_PARM_CYCLE_DATES_PK
	PRIMARY KEY(OBJID);
	
ALTER TABLE BCK_PARM_CYCLE_DATES ADD CONSTRAINT BCK_PARM_CYCLE_DATES_FK1
	FOREIGN KEY (CUST_TYPE_UID) REFERENCES BCK_PARM_CUST_TYPE (OBJID);
	
CREATE UNIQUE INDEX BCK_PARM_CYCLE_DATES_IDX1 ON BCK_PARM_CYCLE_DATES 
	(CYCLE_CODE, END_DATE, DUE_DATE, CUST_TYPE_UID);

CREATE INDEX BCK_PARM_CYCLE_DATES_IDX2 ON BCK_PARM_CYCLE_DATES 
	(END_DATE);

CREATE INDEX BCK_PARM_CYCLE_DATES_IDX3 ON BCK_PARM_CYCLE_DATES 
	(DUE_DATE);

CREATE INDEX BCK_PARM_CYCLE_DATES_IDX4 ON BCK_PARM_CYCLE_DATES 
	(CUST_TYPE_UID);
	
-- Table: BCK_PARM_NF_TAX_THRESHOLD
CREATE TABLE BCK_PARM_NF_TAX_THRESHOLD (
	OBJID 	            NUMBER(19,0)	NOT NULL, 
	TAX_TYPE			INTEGER			NOT NULL,
	LOWER_LIMIT			NUMBER(19,4)			,
	UPPER_LIMIT			NUMBER(19,4)			,
	HINT_MESSAGE		VARCHAR2(128)			,
	CUSTOM_1	    	VARCHAR2(30)			,
	CUSTOM_2            VARCHAR2(30)			,
	CUSTOM_3            VARCHAR2(30)
);


ALTER TABLE BCK_PARM_NF_TAX_THRESHOLD ADD CONSTRAINT BCK_PARM_NF_TAX_THRESHOLD_PK
	PRIMARY KEY(OBJID);

CREATE UNIQUE INDEX BCK_PARM_NF_TAX_THRESHOLD_DIX1 ON BCK_PARM_NF_TAX_THRESHOLD (TAX_TYPE);


