
DROP VIEW BCK_CYCLE_DM_VIEW;

DROP TABLE BCK_CONSEQUENCE_ATTR;
DROP TABLE  BCK_CONSEQUENCE;

DROP TABLE BCK_PARM_OCC_THRESHOLD;
DROP TABLE BCK_PARM_USAGE_THRESHOLD;
DROP TABLE BCK_PARM_NF_THRESHOLD;
DROP TABLE BCK_PARM_INVOICE_THRESHOLD;

DROP TABLE BCK_PARM_CUST_TYPE;

DROP TABLE BCK_ACCOUNT_DM;
DROP TABLE BCK_CARRIER_DM;
DROP TABLE BCK_CARRIER_DATA;
DROP TABLE BCK_CYCLE_DM;
DROP TABLE BCK_GEO_DM;
DROP TABLE BCK_TAX_TYPE;
DROP TABLE BCK_FISCAL_CODE;
DROP TABLE BCK_TAX_RATE;
DROP TABLE BCK_TIME_DM;
DROP TABLE BCK_RULE;
DROP TABLE BCK_RULE_TYPE;

DROP SEQUENCE BCK_CONSEQUENCE_UID;
DROP SEQUENCE BCK_DIMENSIONS_UID;
